# REPORTS REQUESTS
GET http://localhost:3001/api/reports/
###
DELETE http://localhost:3001/api/reports/656e85353ad1b59612304e30
###
POST http://localhost:3001/api/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhYnNrbm93cyIsImlkIjoiNjU2ZTBlM2RiMWY4NjA5MTJhN2U3Y2QxIiwiaWF0IjoxNzAxNzM5NjY3LCJleHAiOjE3MDE3NDMyNjd9.AEOHAU9bUL6Y4iBMzU6rYTK7VCBo9vBvLxPrrXXeOHM

{
  "location": "TEST",
  "title": "TEST1",
  "category": "TEST2",
  "body": "TEST3"
}



# USERS REQUEST
###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "netcs",
  "name": "Kenneth Cabobos",
  "password": "netcs"
}
###
DELETE http://localhost:3001/api/users/656e1194b1f860912a7e7cec



# ROUTES REQUESTS
###
GET http://localhost:3001/api/routes


# LOGIN REQUESTS
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "cabsknows",
  "password": "cabsknows"
}

